[project]
name = "server"
version = "0.1.0"
description = "FastAPI Backend for Duolingo Clone"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "pydantic-settings>=2.15.0",
    "sqlalchemy>=2.0.52",
    "psycopg2-binary>=2.9.10",
]

[tool.fastapi]
entrypoint = "app.main:app"
